---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[ms-solr5::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      solr5:
        version: '5.3.0'
      ftp_active_mode: false
      customer: atx
